### PR TITLE
Added support for pixelformat 1, config verbose option, no-video and no-gui

### PR DESCRIPTION
**Pull request by fspijkerman**

### CODE REVIEW

**Comment by PinkyJie** [comment]
Hey @fspijkerman, any channce you can trigger a github action build for this PR so I can download the artifact to my TV and have a test? I believe my TV is also `pixelformat 1`.

```
root@LGwebOSTV:/media/developer/apps/usr/palm/services/org.webosbrew.piccap.service# LD_LIBRARY_PATH=. ./hyp
erion-webos -b libdile_vt -a 192.168.5.116
[DILE_VT] supportScaleUp: 1; (3840x2160)
[DILE_VT] supportScaleDown: 1; (320x240)
[DILE_VT] maxResolution: 3840x2160
[DILE_VT] input deinterlace: 1; display deinterlace: 1
[DILE_VT] scaledown limit, overriding to 320x240
[DILE_VT] framerate divider: 1
[DILE_VT] frametime: 8634; estimated fps before divider: 115.82117
[DILE_VT] frametime: 8344; estimated fps after divider: 119.84660
[DILE_VT] vfbs: 5; planes: 2
[DILE_VT] pixelFormat: 1; width: 320; height: 240; stride: 320...
[DILE_VT] vfb[0][0] = 0x6e400000
[DILE_VT] vfb[0][1] = 0x6e45f000
[DILE_VT] vfb[1][0] = 0x6e413000
[DILE_VT] vfb[1][1] = 0x6e469000
[DILE_VT] vfb[2][0] = 0x6e426000
[DILE_VT] vfb[2][1] = 0x6e473000
[DILE_VT] vfb[3][0] = 0x6e439000
[DILE_VT] vfb[3][1] = 0x6e47d000
[DILE_VT] vfb[4][0] = 0x6e44c000
[DILE_VT] vfb[4][1] = 0x6e487000
[DILE_VT] framerate: 0.171605 FPS
Start connection loop
[DILE_VT] framerate: 13.521041 FPS
[DILE_VT] framerate: 10.188411 FPS
[DILE_VT] framerate: 11.987715 FPS
[DILE_VT] framerate: 9.799534 FPS
[DILE_VT] framerate: 9.126389 FPS
```

**Comment by Informatic** [comment]
Sadly even I can't do that. Will merge that in though in a couple of hours.

**Comment by fspijkerman** [comment]
> Hey @fspijkerman, any channce you can trigger a github action build for this PR so I can download the artifact to my TV and have a test? I believe my TV is also `pixelformat 1`.
> 
> ```
> root@LGwebOSTV:/media/developer/apps/usr/palm/services/org.webosbrew.piccap.service# LD_LIBRARY_PATH=. ./hyp
> erion-webos -b libdile_vt -a 192.168.5.116
> [DILE_VT] supportScaleUp: 1; (3840x2160)
> [DILE_VT] supportScaleDown: 1; (320x240)
> [DILE_VT] maxResolution: 3840x2160
> [DILE_VT] input deinterlace: 1; display deinterlace: 1
> [DILE_VT] scaledown limit, overriding to 320x240
> [DILE_VT] framerate divider: 1
> [DILE_VT] frametime: 8634; estimated fps before divider: 115.82117
> [DILE_VT] frametime: 8344; estimated fps after divider: 119.84660
> [DILE_VT] vfbs: 5; planes: 2
> [DILE_VT] pixelFormat: 1; width: 320; height: 240; stride: 320...
> [DILE_VT] vfb[0][0] = 0x6e400000
> [DILE_VT] vfb[0][1] = 0x6e45f000
> [DILE_VT] vfb[1][0] = 0x6e413000
> [DILE_VT] vfb[1][1] = 0x6e469000
> [DILE_VT] vfb[2][0] = 0x6e426000
> [DILE_VT] vfb[2][1] = 0x6e473000
> [DILE_VT] vfb[3][0] = 0x6e439000
> [DILE_VT] vfb[3][1] = 0x6e47d000
> [DILE_VT] vfb[4][0] = 0x6e44c000
> [DILE_VT] vfb[4][1] = 0x6e487000
> [DILE_VT] framerate: 0.171605 FPS
> Start connection loop
> [DILE_VT] framerate: 13.521041 FPS
> [DILE_VT] framerate: 10.188411 FPS
> [DILE_VT] framerate: 11.987715 FPS
> [DILE_VT] framerate: 9.799534 FPS
> [DILE_VT] framerate: 9.126389 FPS
> ```

Build is running now

**Comment by PinkyJie** [comment]
Had a quick test, is this warning expected?
Screen Shot 2021-12-29 at 20 18 57

**Comment by Informatic** [comment]
Yes. That's a message reported by the library we use for UI capture on all platforms, and there seems like there's nothing we can do.

**Pull request merged**
