### PR TITLE
WIP uni{fied,versal} capture library/module

### PR DESCRIPTION
**Pull request by Informatic**
This is a work in progress branch with "new" synchronous capture backend interface, unified for both UI and Video layer capture, where all pixel format conversion, scaling and blending is extracted into a common "unicapture" module.

* `backends` now expose a simple, unified synchronous interface for a specific layer capture (ie. we now have separate backends for video layers - `dile_vt`, `vtcapture`, and ui layers - `gm` and `halgal`)
* `unicapture` module is responsible for backend initialization, frame keeping (vsync) and merging/blending/conversion of different layers.
* `converter` is responsible for converting frames between colorspaces (via libyuv), intentionally used only in `unicapture`
* `service` is a module that binds `unicapture` module with `hyperion_client` and exposes Luna bus management service
* `settings` is a module responsible for converting `settings_t` structure to/from JSON objects and files (stored in `config.json` file)
* `main` only handles initialization and startup of `service`

Notable changes:
* Added support for UI capture when combined with `dile_vt`
* Added UI/video backend autodetection (default)
* Added support for automatic pausing of capture when the TV is going to suspend mode (QuickStart+)
* Added `"vsync": false` option that will help with issues like #30 ("fake" vsync signal will be issued every `1/FPS` seconds, instead of using video backend waiting method)
* Unified support for `novideo`/`nogui` options in all backends
* Fixed/improved FPS counting/limiting on all platforms
* `/status` luna service endpoint returns current framerate and info about currently running capture modules
* Disabling autostart will remove the `init.d` symlink properly now
* General stability improvements
* Code has been reformatted using `clangd`/`clang-format`

Known issues:
* TODO: Backend/resolution change requires service kill and restart
* Due to some luna endpoint changes current PicCap GUI does not fully work properly yet
* `libvt` backend has not been ported to "v2" backend interface, and is effectively broken after merging this

Supersedes:
* #47
* #48 - added `vsync` flag
* #40 - fixed frame pace handling including optional vsync
* #21 - contains support for libgm & libhal_gal UI capture support

### CODE REVIEW

**Comment by chbartsch** [comment]
FYI: You can find my work in progress on the halgal/vtcapture side [here](https://github.com/chbartsch/hyperion-webos/tree/unicapture-vtcapture-halgal).

If I can help with stuff or test things just let me know. ;)

**Comment by TBSniller** [comment]
@Informatic: Hope its okay for you, I have commited a change in your pull request. 
If the service is not running as root, but graphic capture is enabled the process crashes while initiating, because its not running as root. This is the case after very first PicCap start.

**Comment by tuxuser** [comment]
- Do we want to enable the -S (--no-service) switch again? (see: https://github.com/webosbrew/hyperion-webos/blob/unicapture/src/main.c#L91)
- `-s/--save-conf` argument still needed? (see: https://github.com/webosbrew/hyperion-webos/blob/6025215d450c0aaf731f0f8d22872e5addbf9ce7/src/main.c#L114-L116)

**Comment by tuxuser** [comment]
When following PRs are merged, unicapture could be merged too:

- PR #79 
- PR #82

**Comment by TBSniller** [comment]
@Informatic @tuxuser @chbartsch after almost one year it's done. Thank you all! <3

**Pull request merged**
